# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DoorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door.Door')),
            ],
            options={
                'ordering': ('door', '-timestamp'),
            },
        ),
    ]
